# Generated by Django 5.1.7 on 2026-07-16 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='SKU')),
                ('category', models.CharField(choices=[('wood', 'Wood / Timber'), ('fabric', 'Fabric / Upholstery'), ('hardware', 'Hardware (Screws, Nails, Hinges)'), ('paint', 'Paint / Polish / Finish'), ('adhesive', 'Adhesive / Glue'), ('foam', 'Foam / Cushion'), ('glass', 'Glass / Mirror'), ('plywood', 'Plywood / MDF / Particle Board'), ('metal', 'Metal (Rods, Pipes, Frames)'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('m', 'Meters'), ('sqft', 'Square Feet'), ('sqm', 'Square Meters'), ('l', 'Liters'), ('sheets', 'Sheets'), ('cuft', 'Cubic Feet')], default='pcs', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Low-stock alert threshold. Alert shows when current stock is at or below this value.', max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Warehouse shelf, zone, or rack identifier.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('alt_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GST Number')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adj', 'Adjustment'), ('dmg', 'Damaged / Wastage')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Invoice or PO number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.material')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.supplier'),
        ),
    ]
