# Generated by Django 5.2.13 on 2026-09-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='inventory_material_current_stock_gte_0'),
        ),
    ]
