# Generated by Django 5.2.13 on 2026-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
