# Generated by Django 5.2.13 on 2026-07-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
        ('measurements', '0005_remove_measurement_unique_measurement_per_customer_garment'),
        ('orders', '0010_rename_measurement_orderitem_dimension_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomGarmentParameter',
            new_name='CustomFurnitureParameter',
        ),
        migrations.RenameModel(
            old_name='CustomGarmentCategory',
            new_name='CustomFurnitureType',
        ),
        migrations.RenameModel(
            old_name='Measurement',
            new_name='FurnitureDimension',
        ),
        migrations.RenameField(
            model_name='furnituredimension',
            old_name='garment_category',
            new_name='furniture_type',
        ),
        migrations.RenameField(
            model_name='furnituredimension',
            old_name='is_sample_product',
            new_name='is_standard_catalog',
        ),
    ]
