# Generated by Django 5.2.13 on 2026-05-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_deposit_amount_order_is_buy_back_and_more'),
    ]

    operations = [
    ]
