# Generated by Django 5.2.13 on 2026-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_is_urgent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='measurement',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='garment_category',
            new_name='furniture_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_red_flagged',
            field=models.BooleanField(default=False, help_text='Mark if the item/catalog is unavailable in-store and must be ordered from a 3rd party.', verbose_name='Red Flag (Outsource Required)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('custom_build', 'Custom Build'), ('rental', 'Rental')], default='custom_build', max_length=20),
        ),
    ]
