# Generated by Django 5.2.13 on 2026-07-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_measurement_orderitem_dimension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_buy_back',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deposit_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_date',
        ),
    ]
