# Generated by Django 5.2.13 on 2026-07-14 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_deposit_amount_remove_order_is_buy_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
