# Generated by Django 5.2.13 on 2026-07-18 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
