# Generated by Django 5.2.13 on 2026-07-18 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
